apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: nginx-jagadish
      image: nginx
      ports:
        - containerPort: 8080
    - name: watcher-jagadish
      image: afakharany/watcher
      ports: 
        - containerPort: 8081
