apiVersion: v1
kind: Pod
metadata:
  name: pod3-github-javadocker
  labels:
    app: hello-world
spec:
  containers:
    - name: nginx-jagadish
      image: jagadishsail/java-docker:1.0.0
      ports:
        - name: nodejs-port
          containerPort: 3000
