apiVersion: v1
kind: Pod
metadata:
  name: pod3-github-img
  lables:
    app: hello-world
spec:
  containers:
    - name: nginx-jagadish
      image: jagadishsail/aws-training
      ports:
        - name: nodejs-port
          containerPort: 3000
