apiVersion: v1
kind: Service
metadat:
  name: helloworld-service
spec:
  ports:
    - nodePort: 31002
      port: 31001
      targetPort: nodejs-port
      protocol: TCP
    selector:
      app: hello-world
    type: NodePort   
